ARG MASTER_IMAGE="gcr.io/scientific-crow-353414/blender-master:v2.9.3"
FROM ${MASTER_IMAGE}

# args
ARG GOOGLE_CLOUD_PROJECT="scientific-crow-353414"
ARG ACCOUNTSERVICE_EMAIL="sa-3dmodels@scientific-crow-353414.iam.gserviceaccount.com"
ARG GCP_CREDENTIALS_FILE="./service-key.json"
ARG BUCKET_EXPORT="gs://scientific-crow-353414-3dmodels/"
ARG ENTRYPOINT_FILE="./entrypoint.sh"

ENV GOOGLE_CLOUD_PROJECT="${GOOGLE_CLOUD_PROJECT}"
ENV ACCOUNTSERVICE_EMAIL="${ACCOUNTSERVICE_EMAIL}"
ENV GCP_CREDENTIALS_FILE="${GCP_CREDENTIALS_FILE}"
ENV MODEL3D_FULL_PATH="/3dmodel"
ENV GOOGLE_APPLICATION_CREDENTIALS="${MODEL3D_FULL_PATH}/${GCP_CREDENTIALS_FILE}"
ENV MODEL3D_FILE="main.blend"
ENV RENDER_EXPORT="${MODEL3D_FULL_PATH}/render/"
ENV ENTRYPOINT_FILE="${ENTRYPOINT_FILE}"
ENV CLOUD_ML_JOB=''
ENV BUCKET_EXPORT="${BUCKET_EXPORT}"

# copying needed files
COPY . ${MODEL3D_FULL_PATH}

# GCP authorize service account
RUN gcloud auth activate-service-account "${ACCOUNTSERVICE_EMAIL}" --key-file "${GOOGLE_APPLICATION_CREDENTIALS}" -q && \
    gcloud config set project "${GOOGLE_CLOUD_PROJECT}";

WORKDIR ${MODEL3D_FULL_PATH}
RUN mkdir -p "${RENDER_EXPORT}"
RUN chmod +x ./${ENTRYPOINT_FILE}
ENTRYPOINT ./${ENTRYPOINT_FILE}
