ARG MASTER_IMAGE="gcr.io/zinc-anvil-320815/blender-master:v2.9.3"
FROM ${MASTER_IMAGE}

# args
ARG GCP_CREDENTIALS_FILE="./service-key.json"
ARG BUCKET_EXPORT="gs://zinc-anvil-320815-3dmodels/"
ARG ENTRYPOINT_FILE="./entrypoint.sh"

ENV MODEL3D_FULL_PATH="/${MODEL3D_PATH}"
ENV MODEL3D_FILE="main.blend"
ENV RENDER_EXPORT="${MODEL3D_FULL_PATH}/render/"
ENV ENTRYPOINT_FILE="${ENTRYPOINT_FILE}"
ENV CLOUD_ML_JOB=''
ENV BUCKET_EXPORT="${BUCKET_EXPORT}"

RUN mkdir -p "${RENDER_EXPORT}"

# copying needed files
COPY . ${MODEL3D_FULL_PATH}

WORKDIR ${MODEL3D_FULL_PATH}
RUN chmod +x ./${ENTRYPOINT_FILE}
ENTRYPOINT ./${ENTRYPOINT_FILE}
