variable "ACCOUNT_SERVICE_EMAIL" {default="#{ACCOUNT_SERVICE_EMAIL}#"}
variable "GOOGLE_APPLICATION_CREDENTIALS" {default="#{GOOGLE_APPLICATION_CREDENTIALS}#"}
variable "GOOGLE_CLOUD_PROJECT" {default="#{GOOGLE_CLOUD_PROJECT}#"}
variable "REGION" {default="#{GOOGLE_APPLICATION_CREDENTIALS}#"}
variable "ZONE" {default="#{GOOGLE_APPLICATION_CREDENTIALS}#"}